### PR TITLE
BREAKING CHANGE: feat: create separate systemd sockets and services for each Pretalx instance

### LINKED ISSUE #29: [bug] Pretalx service cannot start with custom pretalx_system_user
The systemd files make a hard assumption about the user and paths based based on the expected username `pretalx_{{ pretalx_instance_identifier }}`, but that can be overwritten by Ansible role parameters.

### PR DESCRIPTION
**Pull request by MikkCZ**
fix #29

### CODE REVIEW

**Review by rixx — COMMENTED** [review]
I wonder if we can get away without this in any way at all. I'd much prefer flexible units over having nearly-redundant units.

Maybe with per-instance env files?

**Comment by MikkCZ** [comment]
I am not too familiar with systemd configuration, but I found `%u` should work as the user who run the unit, and that there is a way to run services as a user, not just root. I tried to adjust the configuration accordingly. Do you think it might work?

What exactly did you meant by env files?

**Comment by MikkCZ** [comment]
I have been studying quite a lot about systemd this evening and I don't thing environment files nor user systemd services are a way to go.

The problem with environment files is that they cannot provide the user the service should be run under. The user must be specified in the unit file, but the only reliable parameter is `%i`, which is the instance identifier.

With user systemd services, it's possible to get the username as `%u`, but making `systemctl - -user` work is a pain and way beyond the scope of what this role should be doing. Even then the management of such service is hard.

I think a viable way to allow at least limited way of username customization is to open a different pull request and introduce a variable for the username prefix (default to `pretalx_` to keep the existing behavior unchanged).

**Comment by rixx** [comment]
Hey! Sorry for my terse first response, and thank you for looking into this further. Agreed that user name customisation is the easier and less invasive solution here, and that user-based systemd services are painful and definitely not what we need here. Thank you for all your work on this!

**Pull request closed without merging**
