### PR TITLE
ci: migrate from Travis CI to GitHub Actions and polish ansible-lint configuration

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by rixx** [comment]
I don't think we need a build matrix here – testing with a single Python version (3.11, I should think) is absolutely sufficient.

(Also, for future reference, when you want to use Python 3.10 in YAML files like that, you have to make it a string, as otherwise YAML will parse it as a number and Python 3.1 is a long time in our past, thankfully.)

**Review by rixx — CHANGES_REQUESTED** [review]
^

**Comment by MikkCZ** [comment]
I also fixed a couple of errors reported by ansible-lint in the latest version. It still complains about `latest` being used for packages installed for Arch. For Debian this was addressed in #35, but I am not familiar with Arch and what is the expected behavior for updates there?

**Review by rixx — APPROVED** [review]
Thank you so much!

**Comment by rixx** [comment]
I'm honestly not sure what to do about Arch here – probably best to listen to the linter, but I can do that post-merge.

**Pull request merged**
