### PR TITLE
BREAKING CHANGE: fix: update default branch to install plugins from

### LINKED ISSUE #24: [bug] Installtion of pretalx_plugins is hardoced to master branch
The `version` parameter for `git` module of the _Intall pretalx plugin_ task is hard-coded to `master`.

https://github.com/pretalx/ansible-pretalx/blob/ca06bfa36c81d13a5925e8f5a8f90465df7f94c0/tasks/package.yml#L165-L171

This creates two issues:
1. It's not possible to install a plugin from a custom brach, tag or commit.
2. "Official" plugins from https://github.com/pretalx/ cannot be checked out, because the repositories switched from `master` to `main` as the default branch name.

### PR DESCRIPTION
**Pull request by MikkCZ**
Change the default branch to install plugins from to `main`, but also enable to change it to any other branch or tag.

fix #24

### CODE REVIEW

**Comment by MikkCZ** [comment]
Now I realize, changing from `master` to `main` might be a breaking change for someone. But it fixes installation of the "official" plugins from https://github.com/pretalx/.

**Review by rixx — APPROVED** [review]
Absolutely sensible, thank you.

**Comment by MikkCZ** [comment]
@rixx I am afraid the merge did not go as planned. The module parameters are got duplicated https://github.com/pretalx/ansible-pretalx/blob/46755f74b28f128e88b61f8cb4c6c5e53d897427/tasks/package.yml#L168-L177

**Comment by MikkCZ** [comment]
The result should be
```yaml
git:
  repo: "{{ item.repository }}" 
  dest: "{{ pretalx_system_home }}/plugins/{{ item.name }}" 
  version: "{{ item.version if item.version is defined else 'main' }}" 
  key_file: "{{ pretalx_system_home }}/.ssh/id_rsa" 
  accept_hostkey: yes 
```

I am not around my laptop with access to GitHub, so I cannot create a new PR right now.

**Comment by rixx** [comment]
Oh GitHub, thy merge conflicts.

**Comment by rixx** [comment]
Fixed in 2cae113c7305b1731cf45afaac83b8305bb29db4.

Somewhat an illustration of why I like small PRs in *theory* but not in *bulk practice*. It never seems to end quite well, unless provided with a strict list of order or multiple rebases (and GitHub refused to rebase this one, and I was too lazy to check it out locally).

**Pull request merged**
